### PR TITLE
failed test for error control from nested function

### PR DESCRIPTION
**Pull request by rodrigolive**
Hi Mamod, I've detected a problem depicted in the last subtest of this test file. Errors thrown (with die()) in nested calls will either hang or just abort completely. Can you take a look or guide me in the right direction so I can fix it?
Thanks!
Rod

### CODE REVIEW

**Comment by mamod** [comment]
Thank you very much for the test, this has been fixed in #8 

can you please add Test::Fatal to MakeFile.pl "TEST_REQUIRES" as it's not a core module, I want to merge this with one commit :)

**Comment by rodrigolive** [comment]
Thanks Mamod, I'm preparing the next pull request with the TEST_REQUIRES dependency.

But in the meanwhile, I was testing master with my own app, and detected a strange behavior with try-tiny not present in v0.3.0. I'm adding a test case for that too.

**Comment by mamod** [comment]
oops, I've been messing with the master branch :)
are you able to fix the conflict, or you can create a new pull request.
Sorry :(

**Comment by mamod** [comment]
@rodrigolive no worries, I did resolve the conflict but your name doesn't appear in the contribution list, by viewing the commit [patch](https://github.com/rodrigolive/JavaScript-Duktape/commit/a6ce8eaa2d2c31a67f6caa80235ed2d12c63d493.patch) it appears that you're using a different user name and email address than those of your github account, you can fix this by adding a secondary email address, I guess!!

**Pull request merged**
